// <auto-generated />
using UnityEngine; using UnityEngine.UI; using TMPro; using AIProject.Core;

namespace AIProject.UI
{
    public class UIGameEntryPanelView : UIView
    {
        public Button Confirm { get; private set; }

        public UIGameEntryPanelView(UIBinding b) : base(b)
        {
            Confirm = b.Get<Button>("Confirm");
        }
    }
}
